name: SaftiSk
version: '1.0'
main: de.safti.saftiSk.SaftiSk
api-version: '1.21'
libraries:
  - org.kohsuke:github-api:2.0-rc.3
  - dev.dejvokep:boosted-yaml:1.3.7
commands:
  saftisk:
    description: Manage the SaftiSk plugin
    permission: saftisk.command
depend:
  - "Skript"